config:
  MD013:
    code_blocks: false
    line_length: 120 # Increased for better readability
    tables: false
    headings: false # Allow long headings
  MD033: false
  MD024: false
  MD029: false
  MD040: false # Allow code blocks without language specified
gitignore: true
ignores:
  - ".github/**/*.md"
