export function Background() {
  return (
    <div className="bg-globes">
      <svg
        className="globe globe-1"
        width="1886"
        height="1886"
        viewBox="0 0 1886 1886"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <ellipse
          cx="942.821"
          cy="942.821"
          rx="500"
          ry="800"
          transform="rotate(15 942.821 942.821)"
          stroke="url(#paint0a)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.821"
          cy="942.821"
          rx="500"
          ry="800"
          transform="rotate(45 942.821 942.821)"
          stroke="url(#paint1a)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.821"
          cy="942.82"
          rx="500"
          ry="800"
          transform="rotate(75 942.821 942.82)"
          stroke="url(#paint2a)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.822"
          cy="942.82"
          rx="500"
          ry="800"
          transform="rotate(105 942.822 942.82)"
          stroke="url(#paint3a)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.822"
          cy="942.821"
          rx="500"
          ry="800"
          transform="rotate(135 942.822 942.821)"
          stroke="url(#paint4a)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.823"
          cy="942.821"
          rx="500"
          ry="800"
          transform="rotate(165 942.823 942.821)"
          stroke="url(#paint5a)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <defs>
          <linearGradient
            id="paint0a"
            x1="941.155"
            y1="1742.82"
            x2="1077.78"
            y2="154.575"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint1a"
            x1="941.154"
            y1="1742.82"
            x2="1077.78"
            y2="154.574"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint2a"
            x1="941.155"
            y1="1742.82"
            x2="1077.78"
            y2="154.574"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint3a"
            x1="941.155"
            y1="1742.82"
            x2="1077.78"
            y2="154.573"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint4a"
            x1="941.155"
            y1="1742.82"
            x2="1077.79"
            y2="154.575"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint5a"
            x1="941.156"
            y1="1742.82"
            x2="1077.79"
            y2="154.575"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
        </defs>
      </svg>
      <svg
        className="globe globe-2"
        width="1886"
        height="1886"
        viewBox="0 0 1886 1886"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <ellipse
          cx="942.82"
          cy="942.822"
          rx="500"
          ry="800"
          stroke="url(#paint0b)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.82"
          cy="942.822"
          rx="500"
          ry="800"
          transform="rotate(30 942.82 942.822)"
          stroke="url(#paint1b)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.82"
          cy="942.821"
          rx="500"
          ry="800"
          transform="rotate(60 942.82 942.821)"
          stroke="url(#paint2b)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.746"
          cy="942.821"
          rx="500"
          ry="800"
          transform="rotate(90 942.746 942.821)"
          stroke="url(#paint3b)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.821"
          cy="942.82"
          rx="500"
          ry="800"
          transform="rotate(120 942.821 942.82)"
          stroke="url(#paint4b)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <ellipse
          cx="942.822"
          cy="942.82"
          rx="500"
          ry="800"
          transform="rotate(150 942.822 942.82)"
          stroke="url(#paint5b)"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <defs>
          <linearGradient
            id="paint0b"
            x1="941.154"
            y1="1742.82"
            x2="1077.78"
            y2="154.576"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint1b"
            x1="941.154"
            y1="1742.82"
            x2="1077.78"
            y2="154.576"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint2b"
            x1="941.154"
            y1="1742.82"
            x2="1077.78"
            y2="154.575"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint3b"
            x1="941.079"
            y1="1742.82"
            x2="1077.71"
            y2="154.575"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint4b"
            x1="941.155"
            y1="1742.82"
            x2="1077.78"
            y2="154.574"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
          <linearGradient
            id="paint5b"
            x1="941.156"
            y1="1742.82"
            x2="1077.79"
            y2="154.574"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#FFF6E5" />
            <stop
              offset="0.35"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="0.65"
              stopColor="#FFF6E5"
              stopOpacity="0"
            />
            <stop
              offset="1"
              stopColor="#FFF6E5"
            />
          </linearGradient>
        </defs>
      </svg>
    </div>
  );
}
